<div class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-white/[0.03]">
    <form action="{{ $action }}" method="POST" class="space-y-5">
        @csrf
        @if ($method !== 'POST') @method($method) @endif
        <div class="grid gap-5 md:grid-cols-2">
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Category</label><select name="product_category_id" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"><option value="">Select Category</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((string) old('product_category_id', $product?->product_category_id) === (string) $category->id)>{{ $category->name }}</option>@endforeach</select>@error('product_category_id')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Name</label><input type="text" name="name" value="{{ old('name', $product?->name) }}" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@error('name')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        </div>
        <div class="grid gap-5 md:grid-cols-3">
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Slug</label><input type="text" name="slug" value="{{ old('slug', $product?->slug) }}" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">SKU</label><input type="text" name="sku" value="{{ old('sku', $product?->sku) }}" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@error('sku')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Meta Retailer ID</label><input type="text" name="meta_retailer_id" value="{{ old('meta_retailer_id', $product?->meta_retailer_id) }}" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
        </div>
        <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Description</label><textarea name="description" rows="3" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">{{ old('description', $product?->description) }}</textarea></div>
        <div class="grid gap-5 md:grid-cols-3">
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Color</label><input type="text" name="color" value="{{ old('color', $product?->color) }}" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Size</label><input type="text" name="size" value="{{ old('size', $product?->size) }}" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Shipping Weight</label><input type="number" step="0.01" name="shipping_weight" value="{{ old('shipping_weight', $product?->shipping_weight) }}" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
        </div>
        <div class="grid gap-5 md:grid-cols-4">
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Image Path</label><input type="text" name="image_path" value="{{ old('image_path', $product?->image_path) }}" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Price</label><input type="number" step="0.01" name="price" value="{{ old('price', $product?->price) }}" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Sale Price</label><input type="number" step="0.01" name="sale_price" value="{{ old('sale_price', $product?->sale_price) }}" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Inventory</label><input type="number" name="inventory_quantity" value="{{ old('inventory_quantity', $product?->inventory_quantity ?? 0) }}" class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
        </div>
        <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Metadata JSON</label><textarea name="metadata" rows="5" class="w-full rounded-xl border border-gray-200 px-4 py-3 font-mono text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">{{ old('metadata', isset($product) && $product?->metadata ? json_encode($product->metadata, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) : '') }}</textarea>@error('metadata')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <label class="flex items-center gap-3 text-sm font-medium text-gray-700 dark:text-gray-300"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $product?->is_active ?? true))> Active product</label>
        <div class="flex items-center gap-3"><button type="submit" class="rounded-lg bg-brand-500 px-4 py-2 text-sm font-medium text-white hover:bg-brand-600">Save Product</button><a href="{{ route('admin.products.index') }}" class="text-sm font-medium text-gray-600 dark:text-gray-300">Cancel</a></div>
    </form>
</div>
